// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewsgmkvzogvpufrucijq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3c2dta3Z6b2d2cHVmcnVjaWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDYzNzUsImV4cCI6MjA2MzMyMjM3NX0.jZI3pco1jNaS8YJvDeQqC1aaJ5387iX4k79XAxYI-K4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);